name: build GCG

# runs on branches and pull requests; doesn't run on tags.
on:
  push:
    branches:
      - 'alpha'

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone private repo
        run: |
          git clone "https://${{ secrets.OR_GITLAB_USERNAME }}:${{ secrets.OR_GITLAB_ACCESS_TOKEN }}@git.or.rwth-aachen.de/gcg/gcg" main
          cd gcg
          git submodule init
          git submodule update
          mkdir build
          cd build
          cmake .. -DPAPILO=OFF -DIPOPT=OFF -DZIMPL=OFF -DGCG_DEV_BUILD=ON
          make -j4
