name: "Setup SCIPOptSuite"

inputs:
  version:
    description: "SCIPOptSuite version to install"
    required: true
    default: "9.0.0"

runs:
  using: "composite"
  steps:
    - name: Cache SCIPOptSuite Package
      uses: actions/cache@v2
      with:
        path: ~/SCIPOptSuite-${{ inputs.version }}-Linux-ubuntu.deb
        key: ${{ runner.os }}-SCIPOptSuite-${{ env.version }}-home

    - name: Install dependencies (SCIPOptSuite)
      run: |
        wget --quiet --no-check-certificate https://github.com/scipopt/scip/releases/download/$(echo "v${{inputs.version}}" | tr -d '.')/SCIPOptSuite-${{ inputs.version }}-Linux-ubuntu20.deb
        sudo apt-get update && sudo apt install -y ./SCIPOptSuite-${{ inputs.version }}-Linux-ubuntu20.deb
      shell: bash
